name: Discord Bot Updates

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      
      - name: Discord Webhook Notification
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: ""
          embed-title: "${{ github.event.head_commit.message }}"
          embed-color: 16776960
          embed-author-name: ${{ github.actor }}
          embed-description: "A push has been made to ISEAL Discord Bot. \nCommit message: ${{ github.event.head_commit.message }}"
          embed-footer-text: "GitHub Actions"
          embed-timestamp: ${{ github.event.head_commit.timestamp }}
          embed-url: ${{ github.event.head_commit.url }}