name: Discord Bot Updates

on:
  push:
    branches:
      - main
      - pre-release

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Set notification color
        id: color
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "color=5814783" >> $GITHUB_OUTPUT
          else
            echo "color=16776960" >> $GITHUB_OUTPUT
          fi

      - name: Discord Webhook Notification
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: ""
          embed-title: "${{ github.event.head_commit.message }}"
          embed-color: ${{ steps.color.outputs.color }}
          embed-author-name: ${{ github.actor }}
          embed-description: "A push has been made to ISEAL Discord Bot (${{ github.ref_name }} branch).\nCommit message: ${{ github.event.head_commit.message }}"
          embed-footer-text: "GitHub Actions"
          embed-timestamp: ${{ github.event.head_commit.timestamp }}
          embed-url: ${{ github.event.head_commit.url }}