name: Pre-release

on:
  push:
    branches:
      - pre-release

jobs:
  release-and-notify:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Get version
        id: package
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
        shell: bash

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ steps.package.outputs.version }}-pre
        run: |
          gh release create "$TAG" \
            --title "Pre-release $TAG" \
            --notes "Pre-release version $TAG" \
            --target ${{ github.sha }} \
            --prerelease

      - name: Discord Webhook Notification
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: ""
          embed-title: "🧪 Bot Pre-release v${{ steps.package.outputs.version }}"
          embed-color: 16776960
          embed-author-name: ${{ github.actor }}
          embed-description: "A new pre-release version of the ISEAL Discord Bot is available.\n\nCommit message: ${{ github.event.head_commit.message }}"
          embed-footer-text: "GitHub Actions"
          embed-timestamp: ${{ github.event.head_commit.timestamp }}
          embed-url: ${{ github.event.head_commit.url }}