name: Release

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Getting the current version
      id: get_version
      run: |
        echo "VERSION::$(grep 'VERSION = ' main.py | cut -d '"' -f 2)" >> $GITHUB_OUTPUT

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}-${{ steps.get_version.outputs.VERSION }}-pre
        release_name: Release ${{ github.ref_name }}-${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: true
