name: Release and Notify

on:
  push:
    branches:
      - main

jobs:
  release-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Get version
        id: package
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
        shell: bash

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ steps.package.outputs.version }}
          release_name: Main Release ${{ steps.package.outputs.version }}
          draft: false
          prerelease: false

      - name: Discord Webhook Notification
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: "New ISEAL Discord Bot release!"
          embed-title: "🎉 Bot Release v${{ steps.package.outputs.version }}"
          embed-color: 5814783
          embed-author-name: ${{ github.actor }}
          embed-description: "A new version of the ISEAL Discord Bot has been released.\n\nCommit message: ${{ github.event.head_commit.message }}"
          embed-footer-text: "GitHub Actions"
          embed-timestamp: ${{ github.event.head_commit.timestamp }}
          embed-url: ${{ github.event.head_commit.url }}